[build]
  command = "npm run build"
  publish = "build" # Assumindo que a pasta de saída do seu build é 'build'

[build.environment]
  # Define a versão do Node.js para o ambiente de build
  NODE_VERSION = "18"

[functions]
  node_bundler = "zisi" # Pode ser 'esbuild' ou 'zisi' dependendo da sua preferência
  # node_runtime = "nodejs18.x" # Esta linha foi removida pois causava erro de sintaxe

[context.production]
  command = "npm install --legacy-peer-deps && npm run build" # Comando de instalação e build para produção
  # Se o comando acima não funcionar, tente:
  # command = "npm install --force && npm run build"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build" # Comando de instalação e build para deploy previews

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build" # Comando de instalação e build para deploys de branch
